<a href="https://colab.research.google.com/github/chaurasia-namrata/tensorflow_tutorial/blob/main/learn_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensorflow Practice 1

---



In [ ]:
%tensorflow_version 2.x
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.6/dist-packages/tensorflow/_api/v2/version/__init__.py'>


# Creating Tensors



In [ ]:
string = tf.Variable("this is string", tf.string)
number = tf.Variable(324, tf.int16)
floating64 = tf.Variable(3.457, tf.float64)
floating16 = tf.Variable(3.487, tf.float16)
print(string)
print(number)
print(floating64)
print(floating16)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'this is string'>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=324>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.457>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.487>


# Rank



In [ ]:
rank1_tensor = tf.Variable(["test"], tf.string)
rank2_tensor = tf.Variable([["test", "ok", "we"], ["test", "yes", "we"]], tf.string)
print(rank1_tensor)
print(rank2_tensor)

<tf.Variable 'Variable:0' shape=(1,) dtype=string, numpy=array([b'test'], dtype=object)>
<tf.Variable 'Variable:0' shape=(2, 3) dtype=string, numpy=
array([[b'test', b'ok', b'we'],
       [b'test', b'yes', b'we']], dtype=object)>


Determine rank

In [ ]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [ ]:
tf.rank(number)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [ ]:
rank1_tensor.shape

TensorShape([1])

In [ ]:
rank2_tensor.shape

TensorShape([2, 3])

Changing Shapes

In [ ]:
tensor1 = tf.ones([1,2,3])
print(tensor1)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)


In [ ]:
tensor2 = tf.reshape(tensor1, [2,3,1])
tensor3 = tf.reshape(tensor2, [3,-1])

print(tensor2)
print(tensor3)

tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


# Types of Tensors



- Variable  (mutable)
- Constant
- Placeholder
- SparseTensor

# Evaluate Tensors
find value of tensors

In [ ]:
with tf.Session() as sess:
  tensor.eval()

AttributeError: ignored

#LINEAR REGRESSION
https://www.tensorflow.org/tutorials/estimator/linear
---





In [ ]:
from __future__ import absolute_import, division, print_function, unicode_literals

import numpy as np

import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import clear_output
from six.moves import urllib

import tensorflow.compat.v2.feature_column as fc  #fc == feature column

import tensorflow as tf

In [ ]:
dftrain = pd.read_csv('https://storage.googleapis.com/tf-datasets/titanic/train.csv')  #train
dfeval = pd.read_csv('https://storage.googleapis.com/tf-datasets/titanic/eval.csv')  #test

print(dftrain.head()) #print top 5 rows

y_train = dftrain.pop('survived') #REMOVE SURVIVED COL
y_eval = dfeval.pop('survived')

print(dftrain.head())
print(y_train)
print(y_eval)

   survived     sex   age  ...     deck  embark_town  alone
0         0    male  22.0  ...  unknown  Southampton      n
1         1  female  38.0  ...        C    Cherbourg      n
2         1  female  26.0  ...  unknown  Southampton      y
3         1  female  35.0  ...        C  Southampton      n
4         0    male  28.0  ...  unknown   Queenstown      y

[5 rows x 10 columns]
      sex   age  n_siblings_spouses  parch  ...  class     deck  embark_town alone
0    male  22.0                   1      0  ...  Third  unknown  Southampton     n
1  female  38.0                   1      0  ...  First        C    Cherbourg     n
2  female  26.0                   0      0  ...  Third  unknown  Southampton     y
3  female  35.0                   1      0  ...  First        C  Southampton     n
4    male  28.0                   0      0  ...  Third  unknown   Queenstown     y

[5 rows x 9 columns]
0      0
1      1
2      1
3      1
4      0
      ..
622    0
623    0
624    1
625    0
626    

#MULTIPLE GPU & CPU 

---



In [3]:
import tensorflow as tf
a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3], name='a')
b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[3, 2], name='b')
c = tf.matmul(a, b)
# Creates a session with log_device_placement set to True.
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
# Runs the op.
print(sess.run(c))

AttributeError: ignored

In [9]:
import tensorflow as tf

with tf.device('/gpu:0'):       # Run nodes with GPU 0
    m1 = tf.constant([[3, 5]])
    m2 = tf.constant([[2],[4]])
    product = tf.matmul(m1, m2)    

sess = tf.compat.v1.Session()
print(sess.run(product))

sess.close()

AttributeError: ignored

In [8]:
import tensorflow as tf

# Construct 2 op nodes (m1, m2) representing 2 matrix.
m1 = tf.constant([[3, 5]])
m2 = tf.constant([[2],[4]])

product = tf.matmul(m1, m2)    # A matrix multiplication op node

sess = tf.compat.v1.Session(config=tf.ConfigProto(log_device_placement=True))
print(sess.run(product))

sess.close()

AttributeError: ignored

In [7]:
import tensorflow as tf
with tf.compat.v1.Session() as sess:
    hello = tf.constant('hello world')
    print(sess.run(hello))
    

b'hello world'
