# Tensorflow Practice 1

---



In [5]:
%tensorflow_version 2.x
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.6/dist-packages/tensorflow/_api/v2/version/__init__.py'>


# Creating Tensors

---



In [11]:
string = tf.Variable("this is string", tf.string)
number = tf.Variable(324, tf.int16)
floating64 = tf.Variable(3.457, tf.float64)
floating16 = tf.Variable(3.487, tf.float16)
print(string)
print(number)
print(floating64)
print(floating16)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'this is string'>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=324>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.457>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.487>


# Rank

---



In [19]:
rank1_tensor = tf.Variable(["test"], tf.string)
rank2_tensor = tf.Variable([["test", "ok", "we"], ["test", "yes", "we"]], tf.string)
print(rank1_tensor)
print(rank2_tensor)

<tf.Variable 'Variable:0' shape=(1,) dtype=string, numpy=array([b'test'], dtype=object)>
<tf.Variable 'Variable:0' shape=(2, 3) dtype=string, numpy=
array([[b'test', b'ok', b'we'],
       [b'test', b'yes', b'we']], dtype=object)>


Determine rank

In [20]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [17]:
tf.rank(number)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [21]:
rank1_tensor.shape

TensorShape([1])

In [22]:
rank2_tensor.shape

TensorShape([2, 3])

Changing Shapes

In [24]:
tensor1 = tf.ones([1,2,3])
print(tensor1)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)


In [29]:
tensor2 = tf.reshape(tensor1, [2,3,1])
tensor3 = tf.reshape(tensor2, [3,-1])

print(tensor2)
print(tensor3)

tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)
